name: projek
description: "TraveLine"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  encrypt: ^5.0.3
  firebase_auth: ^4.19.4
  firebase_core: ^2.28.0
  firebase_database: ^10.5.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  animate_do: ^3.0.2
  shape_of_view_null_safe: ^2.0.0
  water_drop_nav_bar: ^2.2.0+5
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.1
  intl: ^0.19.0
  quickalert: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.0
  animated_splash_screen: ^1.3.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.16.1
  image_picker: ^1.1.1
  firebase_storage: ^11.7.5
  curved_navigation_bar: ^1.0.3
  url_launcher: ^6.2.6
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.1
  flutter_config: ^2.0.2
  location: ^6.0.0
  permission_handler: ^11.3.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/user/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Black.ttf
        - asset: fonts/Inter-ExtraBold.ttf
        - asset: fonts/Inter-ExtraLight.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Thin.ttf